services:
  mongo:
    image: mongo
    restart: always
#    environment:
#      認証設定したほうがいいけどめんどくさい！！
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
    command: "mongod --bind_ip_all --config /etc/mongod.conf"
    hostname: db-server
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/configdb:/data/configdb
      - ./mongodb/mongod.conf:/etc/mongod.conf

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
